### ISSUE TITLE
New anaphoric forms?

### ISSUE THREAD

**Issue by goderich** [jsmaniac/anaphoric#9]
Would you be interested in adding more anaphoric forms, such as anaphoric map and filter? I've used these anaphoric functions in Elisp (the dash.el library), and found them to be very convenient at times.

**Comment by SuzanneSoy** [comment]
Sure, sounds like a nice idea :)

Do note this repository also aims to serve as an example on how to build a "good" racket library, so I'm pretty stringent on having 100% documentation coverage and 100% test coverage (I'm not obsessive over the 100% for my other libs, just for this one since it's a very simple lib that is more of an illustration than a full-blown package with lots of bells and whistles).

A pull request would be welcome, if you open one I'll make sure to update the CI script to run on travis-ci.com or more probably GitHub Actions (travis-ci.org finally stopped its service, and as nice as Travis is the .com version is a bit of a mess to migrate things to, the pricing is unclear and the .com version wouldn't understand my `.travis-ci.yml` for the .org version, so I kinda gave up).

**Comment by goderich** [comment]
Sure, give me a couple of days to write the docs and the tests, and I'll submit a PR!

**Comment by SuzanneSoy** [comment]
Closed by @goderich's PR #10, thanks a lot!
